name: lint

on:
  push:
    branches: [ master, main ]
  pull_request:

jobs:
  lint:
    name: shellcheck
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script:
          - ubuntu.sh
          - centos.sh
          - alpine.sh
    steps:
      - uses: actions/checkout@v4

      - run: sudo apt-get install -y shellcheck

      - name: Run shellcheck
        run: |
          shellcheck ${{ matrix.script }}
