name: test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        container:
          - ubuntu:20.04
          - ubuntu:18.04
          - ubuntu:16.04
          - debian:buster
          - debian:stretch
          - debian:bullseye
          # - centos:centos8
          - centos:centos7
          # - fedora:32
          # - fedora:31
          # - fedora:30
          - alpine:3.19
          - alpine:3.16

    container:
      image: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v3

      # https://unix.stackexchange.com/a/744408/48776
      - name: Prep on Debian stretch
        if: ${{ startsWith(matrix.container, 'debian') && endsWith(matrix.container, 'stretch') }}
        run: |
          cp /etc/apt/sources.list /etc/apt/sources.list.backup
          cat << 'SRC' > /etc/apt/sources.list
          deb http://archive.debian.org/debian-security stretch/updates main
          deb-src http://archive.debian.org/debian-security stretch/updates main

          deb http://archive.debian.org/debian stretch main
          deb-src http://archive.debian.org/debian stretch main
          SRC

      - name: Prep on Debian/Ubuntu
        if: ${{ startsWith(matrix.container, 'ubuntu') || startsWith(matrix.container, 'debian') }}
        run: |
          apt-get update
          apt-get install -y curl

      - name: Install on Debian/Ubuntu
        if: ${{ startsWith(matrix.container, 'ubuntu') || startsWith(matrix.container, 'debian') }}
        # The following environment variables are to prevent installation of
        # tzdata showing interactive prompt starting with ubuntu:20.04.
        env:
          DEBIAN_FRONTEND: noninteractive
          DEBCONF_NONINTERACTIVE_SEEN: true
          TZ: Etc/GMT
        run: |
          cat ubuntu.sh | bash

      - name: Install on CentOS
        if: ${{startsWith(matrix.container, 'centos') || startsWith(matrix.container, 'fedora') }}
        run: |
          cat centos.sh | bash

      - name: Install on Alpine
        if: ${{startsWith(matrix.container, 'alpine') }}
        run: |
          cat alpine.sh | sh

      - name: Try help
        run: |
          plantuml -h
