name: test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: |
          cat ubuntu.sh | sudo bash
      - name: Help
        run: |
          plantuml -h
  test-centos:
    name: Test on CentOS (Docker)
    runs-on: ubuntu-latest
    container:
      image: centos7
    steps:
      - uses: actions/checkout@master
      - name: Install
        run: |
          cat centos.sh | sudo bash
      - name: Help
        run: |
          plantuml -h