name: test

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  schedule:
    # Run tests weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Ubuntu containers
          - { image: "ubuntu:16.04", os: "ubuntu", checkout: "manual", script: "ubuntu.sh" }
          - { image: "ubuntu:18.04", os: "ubuntu", checkout: "manual", script: "ubuntu.sh" }
          - { image: "ubuntu:20.04", os: "ubuntu", checkout: "v4", script: "ubuntu.sh" }
          - { image: "ubuntu:22.04", os: "ubuntu", checkout: "v4", script: "ubuntu.sh" }
          - { image: "ubuntu:24.04", os: "ubuntu", checkout: "v4", script: "ubuntu.sh" }

          # Debian containers
          - { image: "debian:stretch", os: "debian", checkout: "manual", script: "debian.sh", eol_repos: true }
          - { image: "debian:buster", os: "debian", checkout: "manual", script: "debian.sh", eol_repos: true }
          - { image: "debian:bullseye", os: "debian", checkout: "v4", script: "debian.sh" }
          - { image: "debian:bookworm", os: "debian", checkout: "v4", script: "debian.sh" }
          - { image: "debian:trixie", os: "debian", checkout: "v4", script: "debian.sh" }

          # CentOS containers
          - { image: "centos:centos7", os: "centos", checkout: "manual", script: "centos.sh", eol_repos: true }
          - { image: "centos:centos8", os: "centos", checkout: "v3", script: "centos.sh", eol_repos: true }
          - { image: "quay.io/centos/centos:stream9", os: "centos", checkout: "v3", script: "centos.sh" }

          # Rocky Linux containers
          - { image: "rockylinux:8", os: "rocky", checkout: "v4", script: "rhel.sh" }
          - { image: "rockylinux:9", os: "rocky", checkout: "v4", script: "rhel.sh" }

          # AlmaLinux containers
          - { image: "almalinux:8", os: "alma", checkout: "v4", script: "rhel.sh" }
          - { image: "almalinux:9", os: "alma", checkout: "v4", script: "rhel.sh" }

          # Fedora containers
          - { image: "fedora:39", os: "fedora", checkout: "v4", script: "fedora.sh" }
          - { image: "fedora:40", os: "fedora", checkout: "v4", script: "fedora.sh" }

          # Alpine containers
          - { image: "alpine:3.18", os: "alpine", checkout: "v4", script: "alpine.sh" }
          - { image: "alpine:3.19", os: "alpine", checkout: "v4", script: "alpine.sh" }
          - { image: "alpine:3.20", os: "alpine", checkout: "v4", script: "alpine.sh" }
          - { image: "alpine:3.21", os: "alpine", checkout: "v4", script: "alpine.sh" }
          - { image: "alpine:3.22", os: "alpine", checkout: "v4", script: "alpine.sh" }

    container:
      image: ${{ matrix.image }}

    steps:
      - name: Fix EOL repositories for CentOS
        if: ${{ matrix.checkout == 'manual' && matrix.os == 'centos' && matrix.eol_repos == true }}
        run: |
          sed -i 's/mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-*
          sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

      - name: Fix EOL repositories for Debian
        if: ${{ matrix.checkout == 'manual' && matrix.os == 'debian' && matrix.eol_repos == true }}
        run: |
          cp /etc/apt/sources.list /etc/apt/sources.list.backup
          # Extract Debian codename from the image name
          CODENAME=$(echo "${{ matrix.image }}" | cut -d':' -f2)
          cat << SRC > /etc/apt/sources.list
          deb http://archive.debian.org/debian-security ${CODENAME}/updates main
          deb-src http://archive.debian.org/debian-security ${CODENAME}/updates main

          deb http://archive.debian.org/debian ${CODENAME} main
          deb-src http://archive.debian.org/debian ${CODENAME} main
          SRC

      - name: Install dependencies for Ubuntu/Debian (manual checkout)
        if: ${{ matrix.checkout == 'manual' && (matrix.os == 'ubuntu' || matrix.os == 'debian') }}
        run: |
          apt-get update
          apt-get install -y git curl

      - name: Install dependencies for CentOS (manual checkout)
        if: ${{ matrix.checkout == 'manual' && matrix.os == 'centos' }}
        run: |
          yum install -y git curl

      - name: Install dependencies for Ubuntu/Debian (non-manual checkout)
        if: ${{ matrix.checkout != 'manual' && (matrix.os == 'ubuntu' || matrix.os == 'debian') }}
        run: |
          apt-get update
          apt-get install -y curl

      - name: Install dependencies for CentOS (non-manual checkout)
        if: ${{ matrix.checkout != 'manual' && matrix.os == 'centos' }}
        run: |
          if command -v dnf >/dev/null 2>&1; then
            dnf install -y curl --allowerasing
          else
            yum install -y curl
          fi

      - name: Install dependencies for Fedora/Rocky/Alma Linux
        if: ${{ matrix.os == 'fedora' || matrix.os == 'rocky' || matrix.os == 'alma' }}
        run: |
          dnf install -y curl --allowerasing

      - name: Install dependencies for Alpine
        if: ${{ matrix.os == 'alpine' }}
        run: |
          apk add curl

      - name: Manual checkout for GLIBC-incompatible containers
        if: ${{ matrix.checkout == 'manual' }}
        run: |
          git clone https://github.com/${{ github.repository }}.git .
          git config --global --add safe.directory /__w/plantuml-install/plantuml-install
          git fetch origin ${{ github.sha }}
          git checkout ${{ github.sha }}

      - name: Checkout code (v4)
        if: ${{ matrix.checkout == 'v4' }}
        uses: actions/checkout@v4

      - name: Checkout code (v3)
        if: ${{ matrix.checkout == 'v3' }}
        uses: actions/checkout@v3

      - name: Install PlantUML
        env:
          DEBIAN_FRONTEND: noninteractive
          DEBCONF_NONINTERACTIVE_SEEN: true
          TZ: Etc/GMT
        run: |
          if [ "${{ matrix.os }}" = "alpine" ]; then
            cat ${{ matrix.script }} | sh
          else
            cat ${{ matrix.script }} | bash
          fi

      - name: Test PlantUML installation
        run: |
          plantuml -version
